# Generated by Django 3.2.9 on 2021-11-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211118_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grade_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.subject'),
            preserve_default=False,
        ),
    ]
