# Generated by Django 3.2.9 on 2021-11-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211118_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_2', to='user.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='subject_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_1', to='user.subject'),
        ),
    ]
