# Generated by Django 3.2.9 on 2021-11-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211118_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sub_2', to='user.subject'),
            preserve_default=False,
        ),
    ]
