# Generated by Django 3.2.9 on 2021-11-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_teacher_subject_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_sub_1', to='user.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_sub_2', to='user.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sub_1', to='user.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_sub_2', to='user.subject'),
        ),
    ]
