# Generated by Django 3.2.9 on 2021-11-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211118_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject_2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_2',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='student',
            name='criteria',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='user.criteria'),
            preserve_default=False,
        ),
    ]
