# Generated by Django 3.2.9 on 2021-11-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211121_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_2',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_3',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_4',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_5',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_6',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_7',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_8',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='criteria_9',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_1', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_10',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_10', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_2', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_3', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_4', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_5',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_5', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_6',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_6', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_7',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_7', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_8',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_8', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_9',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_9', to='user.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='g_2', to='user.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='g_3', to='user.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade_4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='g_4', to='user.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade_5',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='g_5', to='user.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='criteria_1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g_1', to='user.grade'),
        ),
    ]
