# Generated by Django 3.2.9 on 2021-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
