# Generated by Django 3.2.9 on 2021-11-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_student_test_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_1', models.CharField(max_length=1)),
                ('criteria_2', models.CharField(max_length=1)),
                ('criteria_3', models.CharField(max_length=1)),
                ('criteria_4', models.CharField(max_length=1)),
                ('criteria_5', models.CharField(max_length=1)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
