# Generated by Django 3.2.9 on 2021-11-23 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_mark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
