# Generated by Django 3.2.9 on 2021-11-23 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_mark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 18, 58, 31, 385864)),
        ),
    ]
